server:
  port: 8080

spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/deep_research?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver


  ai:
    dashscope:
      api-key: sk-3906fd9bb7044413911675be69711fdc
      chat:
        options:
          model: qwen-vl-max
      embedding:
        options:
          model: text-embedding-v3 # Embedding


# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.ai.ai_research_agent.handler  # 扫描类型处理器包